version: '3.7'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - '9090:9090'
        volumes:
            - './docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'

    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_INSTALL_PLUGINS=grafana-piechart-panel
        ports:
            - '3000:3000'
