spring:
    profiles:
        default: dev
        active: dev
        group:
            dev: dev,swagger


management:
    metrics:
        export:
            prometheus:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        prometheus:
            enabled: true
        metrics:
            enabled: true


springdoc:
    api-docs:
        path: '/api-docs'
    show-actuator: true
    pathsToMatch:
        - '/v1'
        - '/api/**'
